version: 2.1

# Configuration des executors
executors:
  php-executor:
    resource_class: small
    shell: /bin/bash
    docker:
      - name: localhost
        image: cimg/php:8.1
  builder-executor:
    resource_class: small
    shell: /bin/bash
    docker:
      - image: cimg/php:8.1-node
        name: localhost
  simple-executor:
    resource_class: small
    shell: /bin/bash
    docker:
      - image: cimg/base:stable
        name: localhost

# Configuration des jobs
jobs:
  build-setup:
    executor: php-executor
    steps:
      - checkout
      - run:
          name: Install Infisical CLI
          command: |
            curl -L https://infisical.com/install.sh | bash
      - run:
          name: Pull secrets from Infisical
          command: |
            infisical pull -m $INFISICAL_MACHINE_ID -s $INFISICAL_MACHINE_SECRET -e production
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: composer install --no-interaction --no-ansi --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  # Les autres jobs restent inchangés

workflows:
  main_workflow:
    jobs:
      - debug-info
      - build-setup
      - lint-phpcs:
          requires:
            - build-setup
      - security-check-dependencies:
          requires:
            - build-setup
      - test-phpunit:
          requires:
            - build-setup
      - hold:
          type: approval
          filters:
            branches:
              only:
                - main
                - master
                - /^release\/.*/
      - deploy-ssh-production:
          requires:
            - hold
          filters:
            branches:
              only:
                - main
                - master
      - deploy-ssh-staging:
          requires:
            - hold
          filters:
            branches:
              only:
                - /^release\/.*/

  container_workflow:
    jobs:
      - build-docker-image:
          filters:
            branches:
              only:
                - master
                - main
                - develop
                - /^feature\/.*/
                - /^release\/.*/
                - /^hotfix\/.*/
                - /^bugfix\/.*/